{{- if .Values.firehoseExporter.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.firehoseExporter.serviceName }}
  labels:
    app.kubernetes.io/name: "metrics"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "metrics-{{ .Values.cfName }}-firehose-exporter-service"
spec:
  type: {{ .Values.firehoseExporter.serviceType }}
  ports:
  - port: {{ .Values.firehoseExporter.externalPort }}
    targetPort: {{ .Values.firehoseExporter.internalPort }}
    protocol: TCP
    name: {{ .Values.firehoseExporter.serviceName }}
  selector:
    app.kubernetes.io/name: "metrics"
    app.kubernetes.io/component: "metrics-{{ .Values.cfName }}-firehose-exporter-service"
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.nginx.serviceName }}
  labels:
    app.kubernetes.io/name: "metrics"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/component: "metrics-{{ .Values.cfName }}-nginx-service"
spec:
{{- if .Values.useLb }}
  type: LoadBalancer
{{- else }}
  type: {{ .Values.nginx.serviceType }}
{{- end }}
{{- if or .Values.kube.external_ip .Values.kube.external_ips .Values.metrics.externalIP  }}
  externalIPs: {{ template "service.externalIPs" . }} 
{{- end }}
  ports:
{{- if and .Values.kube.external_metrics_port (or .Values.kube.external_ip .Values.kube.external_ips) }}
  - port: {{ .Values.kube.external_metrics_port }}
{{- else }}
  - port: {{ .Values.nginx.externalPort }}
{{- end }}
    targetPort: 443
    protocol: TCP
    name: nginx
  selector:
    app.kubernetes.io/name: "metrics"
    app.kubernetes.io/component: "metrics-{{ .Values.cfName }}-firehose-exporter-service"
